apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: folex-dev
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "folex"
        - name: RABBITMQ_DEFAULT_PASS
          value: "folex"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
