apiVersion: v1
kind: Secret
metadata:
  name: workflow-secrets
  namespace: folex-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://folex-postgres-server-dev.postgres.database.azure.com:5432/camunda-db-dev?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "order"
  SPRING_DATASOURCE_PASSWORD: "order"
  CAMUNDA_BPM_ADMIN_USER_ID: "folex"
  CAMUNDA_BPM_ADMIN_USER_PASSWORD: "folex"
  SPRING_RABBITMQ_HOST: "rabbit"
  SPRING_RABBITMQ_USERNAME: "folex"
  SPRING_RABBITMQ_PASSWORD: "folex"
  FOLEX_API_ORDER: "http://order:8080"
  FOLEX_API_FACTORY: "http://factory:8080"