apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  namespace: folex-dev
  labels:
    app: workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
      - name: workflow-service
        image: training16.azurecr.io/folex
        envFrom:
        - configMapRef:
            name: workflow-config
        ports:
        - containerPort: 8080