apiVersion: v1
kind: Service
metadata:
  name: factory-service
  namespace: folex-dev
  labels:
    app: factory

spec:
  selector:
    app: factory
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
