apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory
  namespace: folex-dev
  labels:
    app: factory

spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory
  template:
    metadata:
      labels:
        app: factory
    spec:
      containers:
      - name: factory
        image: training16.azurecr.io/folex/factory:{{ .Values.factoryImage.tag }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 20m
