apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: folex-dev-test
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.11-management-alpine
        envFrom:
          - secretRef:
              name: rabbit-secrets
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
