apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wedding-watches-hpa
  namespace: folex-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wedding-watches
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
