apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workflow-hpa
  namespace: folex-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workflow
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 